### ISSUE TITLE
Feature: User can search for a book

### ISSUE THREAD

**Issue by jessicagrayson** [jessicagrayson/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a book

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create an API-integrated search bar that allows user to locate and select a book that they have read. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/jessicagrayson/ajax-project/assets/98129876/7c71486a-0fd8-44f2-a273-4ed21cadd5cc)
![image](https://github.com/jessicagrayson/ajax-project/assets/98129876/d1b0e81f-c253-4930-9b61-d23a60df74d3)
![image](https://github.com/jessicagrayson/ajax-project/assets/98129876/4d08a40a-8ffd-4a83-825e-8ecf9949f935)
![image](https://github.com/jessicagrayson/ajax-project/assets/98129876/44542856-b9c4-49fb-b1e2-abe272f6ab2e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create HTML layout for page utilizing responsive layout classes
- [x]  Create HTML for search bar and ul that entries will be appended to
- [x]  Add magnifying glass icon to search bar 
- [x]  Apply 'data-view="entry-form"' element to search bar
- [x] Apply 'data-view="entry-view"' element to ul
- [x]  In JavaScript create a data model object with properties for view, an entries array, editing, and nextEntryId
- [x] Write CSS styles for mobile first
- [x] Adjust CSS to fluidly adapt to desktop view
- [x] Ensure that search bar input is required
- [x] Incorporate OpenLibrary API search functionality to search bar
- [ ] Add an 'input' event listener to the search bar that searches API as user types into the search bar and populates a dropdown list of possible matches
- [ ] Add a click event to the dropdown list of possible matches which allows user to select a match from the dropdown
- [x] Add a 'submit' event listener to the magnifying glass icon which enables user to submit their choice
- [ ] When user submits a choice, should assign an entryId property to the new entry data object from the data model's nextEntryId property and increment nextEntryId property by one 
- [ ] 'Submit' adds new object to beginning of data model's array of entries
- [ ] 'Submit' resets the form
- [ ] 'Submit' swaps to "entries" view
- [ ] In data.js file, add a 'beforeunload' event listener to the window object that serializes the data model as  JSON and stores JSON in localStorage
- [ ] In data.js  add a conditional statement to parse JSON data to confirm if present and if so, assigns it to the data variable so that additional entries can be added
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary 
- [ ] Test all functionality again in a private browsing session
- [ ] Fix all errors
