### ISSUE TITLE
Feature: User can store an entry

### ISSUE THREAD

**Issue by jessicagrayson** [jessicagrayson/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can store books as entries

## 📐 Functionality

> User can select and store books that they have read from a list of API generated matches

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Possible Matches](https://github.com/jessicagrayson/ajax-project/assets/98129876/90486581-31ff-4b10-be39-ea888729307d)

![New entry populated from API search](https://github.com/jessicagrayson/ajax-project/assets/98129876/6f287a4a-0249-4876-8ff5-5311d4e37135)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add click event to each <tr> that retrieves values from the <td> elements in the row
- [ ] Add a submit event listener to the forward arrow icon that:
      - [ ] Hides results table and displays new entry form
      - [ ] Pre-populates entry form with <td> values and an empty notes 
       field    
- [ ] Add a "save" button to the entry form
- [ ] Add a submit event listener to the button with the following functionality:
      - [ ] Creates a new object with the <td> and notes values
      - [ ] Adds an entryId to the object
      - [ ] Adds new object to beginning of data model's array of entries
      - [ ] Resets form
      - [ ] Increments the nextEntryId property of the data model so that each 
             entry receives a unique ID.
- [x] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores JSON in localStorage
- [x] In data.js, include a conditional statement that: 
      - [ ] Checks if there is a JSON data model in localStorage
      - [ ] If there is, parse it and assign it to the initial data variable so that the 
             user can continue to add new entries
- [ ]  Test the app by submitting new entries and reload the page to confirm that:
        - [ ] the data model is being saved to localStorage before each page reload
        - [ ] each new entry object is receiving an incrementing entryId property
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary
- [ ] Test functionality again in a private browsing session
- [ ] Fix all errors
